291 feature request transaction filters
telosnetwork/open-block-explorer pull request #342
Opened 2022-09-21 13:14 UTC by WikusKriek

# Pull Request Template

## Description

Transaction table filters. 
Added continious requests to get latest transaction updates on network page.
fixed continious requests does not stop on page navigate.
![image](https://user-images.githubusercontent.com/41372145/191512623-0c384ecb-9b55-473f-b8cf-f8d3a2d0c571.png)
![image](https://user-images.githubusercontent.com/41372145/191512673-494399e1-d2f7-4220-9107-86b16540d916.png)
![image](https://user-images.githubusercontent.com/41372145/191512733-f8a51993-5b54-420a-95c1-f3a212ef74ae.png)

Fixes #291 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-09-21 17:08 UTC, donnyquixotic requested changes

2022-09-21 17:08 UTC, donnyquixotic commented on src/components/TransactionsTable.vue
> +          .q-pa-md(style='max-width: 300px')
remove inline style to a class

2022-09-21 17:08 UTC, donnyquixotic commented on src/components/TransactionsTable.vue
> +          .q-pa-md(style='max-width: 300px')
remove inline style to a class

2022-09-21 17:08 UTC, donnyquixotic commented on src/components/TransactionsTable.vue
> +          .q-pa-md(style='max-width: 300px')
remove inline style to a class

2022-09-22 07:09 UTC, WikusKriek commented on src/components/TransactionsTable.vue
> +          .q-pa-md(style='max-width: 300px')
Done

2022-09-22 22:04 UTC, donnyquixotic approved these changes

2022-09-22 22:05 UTC, merged