fix: core rex balance
telosnetwork/open-block-explorer pull request #351
Opened 2022-09-28 11:48 UTC by WikusKriek

# Pull Request Template

## Description

Fixed total staked value on account page.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-09-28 21:25 UTC, donnyquixotic approved these changes

2022-09-29 17:19 UTC, Kersten-TCD requested changes
@WikusKriek please check Telegram message in OBE-Dev for details.

2022-10-02 00:27 UTC, donnyquixotic approved these changes

2022-10-05 13:17 UTC, Kersten-TCD requested changes
Balance of "staked by others" and "staked" still shows a small difference which I can not explain by staked CPU or NET. There seems to be something different not in order. Difference  for reference account approx. 65 TLOS will staked is less than 3 TLOS.

There is another bug when viewing the account without being signed in. "Staked" balance shows entirely different balance than "staked by others", also total only shows balance of "staked" which is incorrect also.

2022-10-10 13:49 UTC, merged