512 autopopulate quantity and acc validation
telosnetwork/open-block-explorer pull request #641
Opened 2023-03-04 13:36 UTC by jaegerfe

# Fixes #512

## Description

- Changed transfer action to have a quantity field that match the precision and add automatically the token in the end. Also, changed 'to' and 'from' to validate the account name.
- Refactored the AccountSearch component to solve some intermitent issues that I sae and to be able to use in the Transfer action too.
- Created a type called ProposalAction since now it's used in more than one component.
- Refactored some console.logs to console.error to remove some of the warnings.
- New TransferAction component.

## Test scenarios

Manually tested all changes considering wrong usernames, quantity input, and others.
Tested uploading a CSV with different formats of quantity: 4.1, 0.011, 345434.0 ...
Tested uploading a CSV with wrong account names to see if AccountSearch would validate the accounts.

## Checklist:
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

2023-03-06 23:46 UTC, donnyquixotic approved these changes

2023-03-13 05:52 UTC, karynemayer requested changes
When using the `remove` button in a list of actions for a proposal, the button doesn't remove the item it belongs to. Instead, it's removing the last item of the list, independently of which remove button you choose.

2023-03-20 21:06 UTC, jaegerfe commented
@karynemayer could you restest it? I had to put some key different that the array index on the render method to avoid Vue reuse mounted components. Also, did some refactors.

2023-03-21 21:35 UTC, karynemayer approved these changes

2023-03-21 22:19 UTC, merged