660 sendreceive label should not change its layout on smaller screens
telosnetwork/open-block-explorer pull request #672
Opened 2023-03-22 19:07 UTC by donnyquixotic

# Fixes #660 

## Test scenarios
- should retain 'send'/'receive' label width on screen resize and mobile (no-wrap)
- should retain date timestamp width on screen resize and mobile (no-wrap)

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file
-   [ ] I have created a new issue with the required translations for the currently supported languages

2023-03-22 22:46 UTC, karynemayer requested changes
On mobile, if you access your wallet, you'll see that some of the content is chopped off. Possibly because there is a maximum width in the table content somewhere?

<img width="432" alt="Screenshot 2023-03-22 at 15 41 15" src="https://user-images.githubusercontent.com/2939354/227055123-e1c24c27-3bfe-449e-b6a5-b017a0fa56f1.png">

2023-03-22 22:46 UTC, karynemayer commented on src/components/transaction/ActionFormat.vue
> +<style  scoped>
Perhaps we should add `lang="scss" here

2023-03-23 02:53 UTC, Viterbo approved these changes

2023-03-23 02:55 UTC, Viterbo approved these changes

2023-03-27 17:58 UTC, EJSG approved these changes

2023-03-28 18:20 UTC, karynemayer approved these changes

2023-03-28 18:21 UTC, merged