Refactoring multichain sidemenu to a selector component
telosnetwork/open-block-explorer pull request #692
Opened 2023-05-04 16:45 UTC by jaegerfe

# Fixes #706 
# Fixes #705

## Description

Improving the UX of multi chain functionality by moving it from the side menu to a menu button and included a tag on the chain logo to indicate when the User is under a testnet environment.

Also, fixed a bug regarding authentication where the system was keeping the account connected when changing the network.

![image](https://user-images.githubusercontent.com/4021973/236270070-1fd7fdcb-0efc-4d5b-9c48-d0d9d373472d.png)
![image](https://user-images.githubusercontent.com/4021973/236270000-ac194955-0a56-4d39-a08c-981587110d5a.png)
![image](https://user-images.githubusercontent.com/4021973/236269946-6321b1d0-b685-494b-9176-0a9710f5dd13.png)

## Test scenarios

- Selected a testnet chain and checked if the testnet tag appears.
- Changed from one chain to another and checked if the environment changes.

## Checklist:
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] I have cleaned up the code in the areas my change touches
-   [X] My changes generate no new warnings
-   [X] I have checked my code and corrected any misspellings
-   [X] I have removed any unnecessary console messages

2023-05-16 14:39 UTC, karynemayer requested changes
Could we include changing the url according to the selected chain?
This would enable link sharing to the precise transaction/account in the specific chain

2023-05-30 18:37 UTC, jaegerfe commented
> Could we include changing the url according to the selected chain? This would enable link sharing to the precise transaction/account in the specific chain
> 
> for example, for telos we should add `?network=telos`, based on the chain name we have on index.ts for each chain

I will do it in a different PR. This one will only change the side menu for the dropdown and update the ENV var name for it. Also, fixed some bugs on authentication regarding when change from one chain to another.

2023-06-09 02:36 UTC, donnyquixotic approved these changes

2023-06-15 23:37 UTC, karynemayer approved these changes

2023-06-15 23:38 UTC, merged