Theme updates
telosnetwork/open-block-explorer pull request #698
Opened 2023-05-11 18:14 UTC by jaegerfe

## Description

Updating EOS and default themes; refactoring some components to improve the possiblity of customization.
- Updating default theme to a dark grey mode;
- Updating EOS theme to represent their branding;
- Updating some components to improve the ability to customization;
- Updating Vote cards to match with the designs on the other pages;

Telos theme:
![image](https://github.com/telosnetwork/open-block-explorer/assets/4021973/a53229ce-b1fc-4860-af32-c36e77da349d)

New cards on Vote page:
![image](https://github.com/telosnetwork/open-block-explorer/assets/4021973/1c161933-7069-4c94-bfb1-82ad09cfdc31)

EOS theme:
![image](https://github.com/telosnetwork/open-block-explorer/assets/4021973/92afaac9-8252-4bd2-a5a7-c0064e3f19a0)

New default theme:
![image](https://github.com/telosnetwork/open-block-explorer/assets/4021973/a4d9587d-e61d-48ed-8c4f-25c2c460514e)

## Test scenarios

Tested the colors with EOS and default theme;
Tested if the new changes were affecting Telos theme;

## Checklist:
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

2023-05-30 13:52 UTC, pongilo commented
Should the jungle 4 follow the same EOS mainnet?

2023-05-30 14:06 UTC, pongilo approved these changes

2023-06-06 21:52 UTC, karynemayer requested changes
Could we also update the logos for the other chains and make sure they use the default theme?

2023-06-09 03:08 UTC, donnyquixotic approved these changes

2023-06-15 19:07 UTC, karynemayer approved these changes

2023-06-15 19:16 UTC, merged