Implement logic for showing mb vs kb for account resources
telosnetwork/open-block-explorer pull request #776
Opened 2023-10-13 22:20 UTC by kylanhurt

# Fixes #716 

## Description

Max size takes precedence since it is arguably more important: used size is only relevant when a significant portion of max size. Logic ignores max size only for accounts that are privileged / system.

## Test scenarios

Checked values on accounts with NET or RAM that is:
a.) less than 1mb
b) less than 1gb but greater than 1mb
c.) greater than 1gb (eosio.evm)
d.) system account (eosio)

## Checklist:

-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] I have cleaned up the code in the areas my change touches
-   [X] My changes generate no new warnings
-   [X] I have checked my code and corrected any misspellings
-   [X] I have removed any unnecessary console messages
-   [X] I have tested for mobile functionality and responsiveness

2023-10-16 19:19 UTC, donnyquixotic requested changes

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +        const determineRamUnit = (size: number) => {
```suggestion
        const determineUnit = (size: number) => {
```
method isn't specif to RAM (used for NET as well)

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                // in most cases the max value unit is more im portant than the
```suggestion
                // base displayed units on max value for readability 
```

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                // used value unit. So we use the max value unit.
```suggestion
```

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                // get max ram number
```suggestion
```

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                // get denominator based on max number
```suggestion
```

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                ramDenominator = determineRamUnit(ramMaxNumber).denominator;
```suggestion
                const ramUnitResult = determineUnit(ramMaxNumber);
                ramDenominator = ramUnitResult.denominator;
                ramUnit.value = ramUnitResult.unit;
```
You only need to call determineUnit once with the same input as the input value never changes.

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                // get units
```suggestion
```

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                ramUnit.value = determineRamUnit(ramMaxNumber).unit;
```suggestion
```
assigned on line 188 via suggesstion

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                const netDenominator = determineRamUnit(netMaxNumber).denominator;
```suggestion
                const netUnitResult = determineUnit(netMaxNumber);
                const netDenominator = netUnitResult.denominator;
                netUnit.value = netUnitResult.unit;
```
You only need to call determineUnit once with the same input as the input value never changes.

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                netUnit.value = determineRamUnit(netMaxNumber).unit;
```suggestion
```
refactored in previous suggestion

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                ramDenominator = determineRamUnit(ramUsedNumber).denominator;
```suggestion
                const ramUnitResult = determineUnit(ramUsedNumber);
                ramDenominator = ramUnitResult.denominator;
                ramUnit.value = ramUnitResult.unit;
```

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +                ramUnit.value = determineRamUnit(ramUsedNumber).unit;
```suggestion
```

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
>              MICRO_UNIT,
```suggestion
```
unnecessary to return, not referenced in template

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
>              KILO_UNIT,
```suggestion
```
unnecessary to return, not referenced in template

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +            MEGA_UNIT,
```suggestion
```
unnecessary to return, not referenced in template

2023-10-16 19:19 UTC, donnyquixotic commented on src/components/AccountCard.vue
> +            GIGA_UNIT,
```suggestion
```
unnecessary to return, not referenced in template
```

2023-10-17 16:50 UTC, kylanhurt commented
@donnyquixotic Comments handled

2023-10-17 17:26 UTC, donnyquixotic approved these changes

2023-10-17 17:27 UTC, merged